name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
    - name: cowsay test
      uses: Code-Hex/neo-cowsay-action@v1
      with:
        message: 'Hello, World with random'
        cow: 'random' # If specified, it shows random ascii art.
        cowsay_on_comment: true
    - name: Lire fichier readme 
      id : readme
      uses: juliangruber/read-file-action@v1
      with:
        path: ./README.md
    - name: Echo readme
      run: cat readme
